services:
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/
    networks:
      - database
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - database

  # redis:
  #   build: redis
  #   ports:
  #     - "8080:80"

volumes:
  data:

networks:
  database:
